# Use the official MySQL base image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=@dmin@123
ENV MYSQL_DATABASE=merodiscount-booking
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=@dmin@123

# Copy SQL scripts to initialize the database (if needed)
# COPY ./sql-scripts/ /docker-entrypoint-initdb.d/

COPY .docker/mysql/conf.d /etc/mysql/conf.d
COPY .docker/mysql/init/init.sql /usr/local/etc/mysql/init.sql

# Expose MySQL port
# EXPOSE 3306

# Start MySQL server
CMD ["mysqld"]
