basePath: /
host: localhost:8000
info:
  contact: {}
  description: This is a Api Endpoints server for using Swagger with Echo.
  title: Swagger  API Endpoints for Demo App
  version: "1.0"
paths:
  /facilities:
    get:
      consumes:
      - application/json
      description: get All data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
      summary: Get Facility List
  /facilities/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: facility ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
      summary: Show Faility
swagger: "2.0"
